export const CONTEXT_UPDARE = 'contextupdate'
export const ADD_BLOCK = 'addblock'
export const BACKSPACE = 'backspace'
export const FOCUS = 'focus'
export const ChANGEFILENAME = 'changefilename'
export const CONTENTFORMAT= 'contentFormat'
export const BLUR = 'blur'
export const CONTENTALIGN = 'contentAlign'